version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi-backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/templates:/app/frontend/templates

  go-server:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
