version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src/app:/app/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: .venv/bin/uvicorn bookmarker.main:app --host 0.0.0.0 --port 8000 --reload