[project]
name = "bookmarkerapp"
version = "0.1.0"
description = "Mozilla Pocket Bookmarker Alternative"
readme = "README.md"
requires-python = ">=3.10.9"
dependencies = [
    'fastapi',
    'pydantic',
    'uvicorn',
    'jinja2',
]
